# Generated by Django 4.2.7 on 2023-11-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedpartner',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trustedpartner',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trustedpartner',
            name='url',
            field=models.URLField(default='logo'),
            preserve_default=False,
        ),
    ]
